services:
  app:
    build: .
    container_name: recordatorio_api
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      MAILGUN_USER: ${MAILGUN_USER}
      MAILGUN_PASS: ${MAILGUN_PASS}
    ports:
      - "8080:8080"
